package edu.hbuas.carm.model.javabean;

import java.io.Serializable;

/**
 * 汽车信息表 ���f���N���X.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Car implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 汽车编号. */
	private Integer carid;

	/** 汽车图片. */
	private String image;

	/** 汽车品牌. */
	private String carname;

	/** 系列. */
	private String series;

	/** 售价. */
	private Float shoujia;

	/** 行驶里程. */
	private Float xingshilicheng;

	/** 颜色. */
	private String color;

	/** 排量. */
	private String pailiang;

	/** 类型. */
	private String leixing;

	/** 所在地. */
	private String suozaidi;

	/**
	 * �R���X�g���N�^.
	 */
	public Car() {
	}

	/**
	 * 汽车编号 ��ݒ肵�܂�.
	 * 
	 * @param carid
	 *            汽车编号
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * 汽车编号 ���擾���܂�.
	 * 
	 * @return 汽车编号
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * 汽车图片 ��ݒ肵�܂�.
	 * 
	 * @param image
	 *            汽车图片
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * 汽车图片 ���擾���܂�.
	 * 
	 * @return 汽车图片
	 */
	public String getImage() {
		return this.image;
	}

	/**
	 * 汽车品牌 ��ݒ肵�܂�.
	 * 
	 * @param carname
	 *            汽车品牌
	 */
	public void setCarname(String carname) {
		this.carname = carname;
	}

	/**
	 * 汽车品牌 ���擾���܂�.
	 * 
	 * @return 汽车品牌
	 */
	public String getCarname() {
		return this.carname;
	}

	/**
	 * 系列 ��ݒ肵�܂�.
	 * 
	 * @param series
	 *            系列
	 */
	public void setSeries(String series) {
		this.series = series;
	}

	/**
	 * 系列 ���擾���܂�.
	 * 
	 * @return 系列
	 */
	public String getSeries() {
		return this.series;
	}

	/**
	 * 售价 ��ݒ肵�܂�.
	 * 
	 * @param shoujia
	 *            售价
	 */
	public void setShoujia(Float shoujia) {
		this.shoujia = shoujia;
	}

	/**
	 * 售价 ���擾���܂�.
	 * 
	 * @return 售价
	 */
	public Float getShoujia() {
		return this.shoujia;
	}

	/**
	 * 行驶里程 ��ݒ肵�܂�.
	 * 
	 * @param xingshilicheng
	 *            行驶里程
	 */
	public void setXingshilicheng(Float xingshilicheng) {
		this.xingshilicheng = xingshilicheng;
	}

	/**
	 * 行驶里程 ���擾���܂�.
	 * 
	 * @return 行驶里程
	 */
	public Float getXingshilicheng() {
		return this.xingshilicheng;
	}

	/**
	 * 颜色 ��ݒ肵�܂�.
	 * 
	 * @param color
	 *            颜色
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * 颜色 ���擾���܂�.
	 * 
	 * @return 颜色
	 */
	public String getColor() {
		return this.color;
	}

	/**
	 * 排量 ��ݒ肵�܂�.
	 * 
	 * @param pailiang
	 *            排量
	 */
	public void setPailiang(String pailiang) {
		this.pailiang = pailiang;
	}

	/**
	 * 排量 ���擾���܂�.
	 * 
	 * @return 排量
	 */
	public String getPailiang() {
		return this.pailiang;
	}

	/**
	 * 类型 ��ݒ肵�܂�.
	 * 
	 * @param leixing
	 *            类型
	 */
	public void setLeixing(String leixing) {
		this.leixing = leixing;
	}

	/**
	 * 类型 ���擾���܂�.
	 * 
	 * @return 类型
	 */
	public String getLeixing() {
		return this.leixing;
	}

	/**
	 * 所在地 ��ݒ肵�܂�.
	 * 
	 * @param suozaidi
	 *            所在地
	 */
	public void setSuozaidi(String suozaidi) {
		this.suozaidi = suozaidi;
	}

	/**
	 * 所在地 ���擾���܂�.
	 * 
	 * @return 所在地
	 */
	public String getSuozaidi() {
		return this.suozaidi;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Car other = (Car) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
